
name: toJson vars

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment variable source'
        type: environment
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: ${{ github.event.inputs.environment }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create file with GitHub context
        run: echo '${{ toJSON(github) }}' > github-context.json

      - name: Print GitHub context from file
        run: cat github-context.json

      - name: Create file with GitHub context
        run: echo '${{ toJSON(secrets) }}' > github-secrets.json

      - name: Print GitHub context from file
        run: cat github-secrets.json

      - name: Update JSON
        run: |
          # Ruta al archivo de destino en el repositorio
          archivo_destino=".github/aws/sm-schema.json"

          # Extraer las claves del archivo de destino
          claves_destino=$(jq -r 'keys[]' "$archivo_destino")

          # Crear un objeto JSON vacío para el resultado
          resultado="{}"

          # Leer el contenido de origen de una variable de entorno de GitHub llamada ORIGEN_JSON
          contenido_origen="${{ toJSON(secrets) }}"

          # Iterar sobre las claves del archivo de destino
          for clave in $claves_destino; do
            # Obtener el valor correspondiente del contenido de origen
            valor_origen=$(echo "$contenido_origen" | jq -r ".$clave")

            # Verificar si el valor es numérico o no nulo
            if [[ "$valor_origen" =~ ^[0-9]+([.][0-9]+)?$ ]] || [ "$valor_origen" == "null" ]; then
              # Agregar la clave y el valor al resultado
              resultado=$(jq --arg clave "$clave" --arg valor "$valor_origen" '. + {($clave): $valor}' <<< "$resultado")
            else
              echo "Valor no válido para la clave $clave: $valor_origen"
            fi
          done

          # Guardar el resultado en el archivo de destino
          echo "$resultado" > "$archivo_destino"

          echo "Archivo resultante:"
          cat "$archivo_destino"



